[2023-02-16 11:59:43,047] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.insert_data manual__2023-02-16T17:59:40.371260+00:00 [queued]>
[2023-02-16 11:59:43,053] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.insert_data manual__2023-02-16T17:59:40.371260+00:00 [queued]>
[2023-02-16 11:59:43,053] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:59:43,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-16 11:59:43,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:59:43,062] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): insert_data> on 2023-02-16 17:59:40.371260+00:00
[2023-02-16 11:59:43,065] {standard_task_runner.py:52} INFO - Started process 74926 to run task
[2023-02-16 11:59:43,067] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1.6_user_processing', 'insert_data', 'manual__2023-02-16T17:59:40.371260+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6_user_processing.py', '--cfg-path', '/tmp/tmpdz0zfgmf', '--error-file', '/tmp/tmp46ftscfv']
[2023-02-16 11:59:43,068] {standard_task_runner.py:80} INFO - Job 252: Subtask insert_data
[2023-02-16 11:59:43,112] {task_command.py:369} INFO - Running <TaskInstance: 1.6_user_processing.insert_data manual__2023-02-16T17:59:40.371260+00:00 [running]> on host Tinmar.
[2023-02-16 11:59:43,162] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6_user_processing
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T17:59:40.371260+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T17:59:40.371260+00:00
[2023-02-16 11:59:43,163] {sql.py:254} INFO - Executing: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    
[2023-02-16 11:59:43,176] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-02-16 11:59:43,211] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-02-16 11:59:43,217] {sql.py:375} INFO - Running statement: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    , parameters: None
[2023-02-16 11:59:43,218] {sql.py:384} INFO - Rows affected: 1
[2023-02-16 11:59:43,234] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1.6_user_processing, task_id=insert_data, execution_date=20230216T175940, start_date=20230216T175943, end_date=20230216T175943
[2023-02-16 11:59:43,285] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-16 11:59:43,319] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
