[2023-02-16 11:57:38,385] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T17:57:32.619139+00:00 [queued]>
[2023-02-16 11:57:38,392] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T17:57:32.619139+00:00 [queued]>
[2023-02-16 11:57:38,393] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:57:38,395] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-16 11:57:38,396] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 11:57:38,405] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-16 17:57:32.619139+00:00
[2023-02-16 11:57:38,409] {standard_task_runner.py:52} INFO - Started process 74178 to run task
[2023-02-16 11:57:38,411] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1.6_user_processing', 'is_api_available', 'manual__2023-02-16T17:57:32.619139+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6_user_processing.py', '--cfg-path', '/tmp/tmpm1f5kr0c', '--error-file', '/tmp/tmpwcj9bv3q']
[2023-02-16 11:57:38,412] {standard_task_runner.py:80} INFO - Job 247: Subtask is_api_available
[2023-02-16 11:57:38,463] {task_command.py:369} INFO - Running <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T17:57:32.619139+00:00 [running]> on host Tinmar.
[2023-02-16 11:57:38,515] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6_user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T17:57:32.619139+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T17:57:32.619139+00:00
[2023-02-16 11:57:38,516] {http.py:122} INFO - Poking: api/
[2023-02-16 11:57:38,525] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-02-16 11:57:38,848] {base.py:301} INFO - Success criteria met. Exiting.
[2023-02-16 11:57:38,859] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1.6_user_processing, task_id=is_api_available, execution_date=20230216T175732, start_date=20230216T175738, end_date=20230216T175738
[2023-02-16 11:57:38,893] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-16 11:57:38,927] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
