[2023-02-15 18:00:01,472] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-02-15T00:00:00+00:00 [queued]>
[2023-02-15 18:00:01,483] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-02-15T00:00:00+00:00 [queued]>
[2023-02-15 18:00:01,484] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-15 18:00:01,485] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-15 18:00:01,485] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-15 18:00:01,497] {taskinstance.py:1377} INFO - Executing <Task(DataprocCreateClusterOperator): create_cluster> on 2023-02-15 00:00:00+00:00
[2023-02-15 18:00:01,501] {standard_task_runner.py:52} INFO - Started process 465979 to run task
[2023-02-15 18:00:01,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '6_dataproc_***', 'create_cluster', 'scheduled__2023-02-15T00:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/Airflow2_0_De_0_a_Heroe/6_dataproc_***.py', '--cfg-path', '/tmp/tmp56s3kj9p', '--error-file', '/tmp/tmpq6vf7fme']
[2023-02-15 18:00:01,510] {standard_task_runner.py:80} INFO - Job 217: Subtask create_cluster
[2023-02-15 18:00:01,597] {task_command.py:369} INFO - Running <TaskInstance: 6_dataproc_airflow.create_cluster scheduled__2023-02-15T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-15 18:00:01,668] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=David S
AIRFLOW_CTX_DAG_ID=6_dataproc_***
AIRFLOW_CTX_TASK_ID=create_cluster
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-15T00:00:00+00:00
[2023-02-15 18:00:01,669] {dataproc.py:591} INFO - Creating cluster: ***-spark-cluster
[2023-02-15 18:00:01,680] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-15 18:00:04,441] {dataproc.py:603} INFO - Cluster already exists.
[2023-02-15 18:02:07,592] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=6_dataproc_***, task_id=create_cluster, execution_date=20230215T000000, start_date=20230216T000001, end_date=20230216T000207
[2023-02-15 18:02:07,620] {local_task_job.py:156} INFO - Task exited with return code 0
