[2023-02-16 12:03:45,600] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T18:02:36.208542+00:00 [queued]>
[2023-02-16 12:03:45,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T18:02:36.208542+00:00 [queued]>
[2023-02-16 12:03:45,609] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 12:03:45,611] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-02-16 12:03:45,612] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-16 12:03:45,621] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-02-16 18:02:36.208542+00:00
[2023-02-16 12:03:45,624] {standard_task_runner.py:52} INFO - Started process 76843 to run task
[2023-02-16 12:03:45,627] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1.6_user_processing', 'is_api_available', 'manual__2023-02-16T18:02:36.208542+00:00', '--job-id', '268', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.6_user_processing.py', '--cfg-path', '/tmp/tmpai90u0we', '--error-file', '/tmp/tmpivfoku5u']
[2023-02-16 12:03:45,628] {standard_task_runner.py:80} INFO - Job 268: Subtask is_api_available
[2023-02-16 12:03:45,686] {task_command.py:369} INFO - Running <TaskInstance: 1.6_user_processing.is_api_available manual__2023-02-16T18:02:36.208542+00:00 [running]> on host Tinmar.
[2023-02-16 12:03:45,742] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.6_user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-02-16T18:02:36.208542+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-16T18:02:36.208542+00:00
[2023-02-16 12:03:45,750] {http.py:122} INFO - Poking: api/
[2023-02-16 12:03:45,761] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2023-02-16 12:03:46,082] {base.py:301} INFO - Success criteria met. Exiting.
[2023-02-16 12:03:46,103] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=1.6_user_processing, task_id=is_api_available, execution_date=20230216T180236, start_date=20230216T180345, end_date=20230216T180346
[2023-02-16 12:03:46,139] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-16 12:03:46,180] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
