[2023-02-15 16:47:45,746] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 7_dataproc_subdags.par_task.avg_uprice scheduled__2023-02-14T00:00:00+00:00 [queued]>
[2023-02-15 16:47:45,754] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 7_dataproc_subdags.par_task.avg_uprice scheduled__2023-02-14T00:00:00+00:00 [queued]>
[2023-02-15 16:47:45,755] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-15 16:47:45,756] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-15 16:47:45,756] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-15 16:47:45,765] {taskinstance.py:1377} INFO - Executing <Task(DataprocSubmitJobOperator): avg_uprice> on 2023-02-14 00:00:00+00:00
[2023-02-15 16:47:45,768] {standard_task_runner.py:52} INFO - Started process 442714 to run task
[2023-02-15 16:47:45,770] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '7_dataproc_subdags.par_task', 'avg_uprice', 'scheduled__2023-02-14T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/Airflow2_0_De_0_a_Heroe/7_dataproc_subdags.py', '--cfg-path', '/tmp/tmp3dyfam8w', '--error-file', '/tmp/tmpv1wyr095']
[2023-02-15 16:47:45,773] {standard_task_runner.py:80} INFO - Job 215: Subtask avg_uprice
[2023-02-15 16:47:45,828] {task_command.py:369} INFO - Running <TaskInstance: 7_dataproc_subdags.par_task.avg_uprice scheduled__2023-02-14T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-15 16:47:45,890] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=David Sanchez
AIRFLOW_CTX_DAG_ID=7_dataproc_subdags.par_task
AIRFLOW_CTX_TASK_ID=avg_uprice
AIRFLOW_CTX_EXECUTION_DATE=2023-02-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-14T00:00:00+00:00
[2023-02-15 16:47:45,892] {dataproc.py:1866} INFO - Submitting job
[2023-02-15 16:47:45,903] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-02-15 16:47:46,427] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/tinmar/.local/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/tinmar/.local/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "Unable to submit job, cluster 'airflow-spark-cluster' is in state DELETING and cannot accept jobs."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.15.10:443 {created_time:"2023-02-15T16:47:46.427300602-06:00", grpc_status:9, grpc_message:"Unable to submit job, cluster \'airflow-spark-cluster\' is in state DELETING and cannot accept jobs."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 1868, in execute
    job_object = self.hook.submit_job(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 462, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 780, in submit_job
    return client.submit_job(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/cloud/dataproc_v1/services/job_controller/client.py", line 520, in submit_job
    response = rpc(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.FailedPrecondition: 400 Unable to submit job, cluster 'airflow-spark-cluster' is in state DELETING and cannot accept jobs.
[2023-02-15 16:47:46,440] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=7_dataproc_subdags.par_task, task_id=avg_uprice, execution_date=20230214T000000, start_date=20230215T224745, end_date=20230215T224746
[2023-02-15 16:47:46,449] {standard_task_runner.py:92} ERROR - Failed to execute job 215 for task avg_uprice (400 Unable to submit job, cluster 'airflow-spark-cluster' is in state DELETING and cannot accept jobs.; 442714)
[2023-02-15 16:47:46,467] {local_task_job.py:156} INFO - Task exited with return code 1
