[2023-02-21T11:48:50.217-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 3_retries.task_b manual__2023-02-21T17:47:58.933454+00:00 [queued]>
[2023-02-21T11:48:50.227-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 3_retries.task_b manual__2023-02-21T17:47:58.933454+00:00 [queued]>
[2023-02-21T11:48:50.228-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T11:48:50.229-0600] {taskinstance.py:1363} INFO - Starting attempt 4 of 4
[2023-02-21T11:48:50.230-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T11:48:50.237-0600] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_b> on 2023-02-21 17:47:58.933454+00:00
[2023-02-21T11:48:50.240-0600] {standard_task_runner.py:54} INFO - Started process 521911 to run task
[2023-02-21T11:48:50.242-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '3_retries', 'task_b', 'manual__2023-02-21T17:47:58.933454+00:00', '--job-id', '658', '--raw', '--subdir', 'DAGS_FOLDER/Apache_Airflow-The_Operators_Guide/3_retries.py', '--cfg-path', '/tmp/tmpmha92199']
[2023-02-21T11:48:50.244-0600] {standard_task_runner.py:83} INFO - Job 658: Subtask task_b
[2023-02-21T11:48:50.245-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Apache_Airflow-The_Operators_Guide/3_retries.py
[2023-02-21T11:48:50.358-0600] {task_command.py:384} INFO - Running <TaskInstance: 3_retries.task_b manual__2023-02-21T17:47:58.933454+00:00 [running]> on host Tinmar.
[2023-02-21T11:48:50.407-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Andrade
AIRFLOW_CTX_DAG_ID=3_retries
AIRFLOW_CTX_TASK_ID=task_b
AIRFLOW_CTX_EXECUTION_DATE=2023-02-21T17:47:58.933454+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-21T17:47:58.933454+00:00
[2023-02-21T11:48:50.408-0600] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-21T11:48:50.409-0600] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5 && exit 1']
[2023-02-21T11:48:50.414-0600] {subprocess.py:86} INFO - Output:
[2023-02-21T11:48:55.416-0600] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-21T11:48:55.427-0600] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-21T11:48:55.429-0600] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=3_retries, task_id=task_b, execution_date=20230221T174758, start_date=20230221T174850, end_date=20230221T174855
[2023-02-21T11:48:55.439-0600] {standard_task_runner.py:102} ERROR - Failed to execute job 658 for task task_b (Bash command failed. The command returned a non-zero exit code 1.; 521911)
[2023-02-21T11:48:55.472-0600] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-21T11:48:55.484-0600] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
