[2023-02-18T18:29:04.881-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-18T18:29:04.907-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-18T00:00:00+00:00 [queued]>
[2023-02-18T18:29:04.908-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T18:29:04.910-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-18T18:29:04.911-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T18:29:04.938-0600] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2023-02-18 00:00:00+00:00
[2023-02-18T18:29:04.945-0600] {standard_task_runner.py:54} INFO - Started process 195761 to run task
[2023-02-18T18:29:04.949-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.5_user_processing', 'insert_data', 'scheduled__2023-02-18T00:00:00+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.5_user_processing.py', '--cfg-path', '/tmp/tmpqbl9l5jp']
[2023-02-18T18:29:04.952-0600] {standard_task_runner.py:83} INFO - Job 503: Subtask insert_data
[2023-02-18T18:29:04.955-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.5_user_processing.py
[2023-02-18T18:29:05.461-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-18T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-18T18:29:05.512-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.5_user_processing
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-18T00:00:00+00:00
[2023-02-18T18:29:05.513-0600] {sql.py:254} INFO - Executing: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    
[2023-02-18T18:29:05.526-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-18T18:29:05.795-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-18T18:29:05.802-0600] {sql.py:375} INFO - Running statement: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    , parameters: None
[2023-02-18T18:29:05.803-0600] {sql.py:384} INFO - Rows affected: 1
[2023-02-18T18:29:05.820-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.5_user_processing, task_id=insert_data, execution_date=20230218T000000, start_date=20230219T002904, end_date=20230219T002905
[2023-02-18T18:29:05.862-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-18T18:29:05.891-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
