[2023-01-31 17:13:51,670] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 2.3_azure_storage_bigquery.transferir_azure_2021 scheduled__2023-01-31T00:00:00+00:00 [queued]>
[2023-01-31 17:13:51,680] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: 2.3_azure_storage_bigquery.transferir_azure_2021 scheduled__2023-01-31T00:00:00+00:00 [queued]>
[2023-01-31 17:13:51,680] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-31 17:13:51,681] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-31 17:13:51,681] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-31 17:13:51,704] {taskinstance.py:1377} INFO - Executing <Task(AzureBlobStorageToGCSOperator): transferir_azure_2021> on 2023-01-31 00:00:00+00:00
[2023-01-31 17:13:51,707] {standard_task_runner.py:52} INFO - Started process 13475 to run task
[2023-01-31 17:13:51,708] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', '2.3_azure_storage_bigquery', 'transferir_azure_2021', 'scheduled__2023-01-31T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/Airflow2.0-De-0-a-Heroe/2.3_azure_storage_bigquery.py', '--cfg-path', '/tmp/tmpwc87o8n9', '--error-file', '/tmp/tmp9ycgul2i']
[2023-01-31 17:13:51,709] {standard_task_runner.py:80} INFO - Job 83: Subtask transferir_azure_2021
[2023-01-31 17:13:51,768] {task_command.py:369} INFO - Running <TaskInstance: 2.3_azure_storage_bigquery.transferir_azure_2021 scheduled__2023-01-31T00:00:00+00:00 [running]> on host Tinmar.
[2023-01-31 17:13:51,859] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Rodrigo N
AIRFLOW_CTX_DAG_ID=2.3_azure_storage_bigquery
AIRFLOW_CTX_TASK_ID=transferir_azure_2021
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-31T00:00:00+00:00
[2023-01-31 17:13:51,869] {base.py:68} INFO - Using connection ID 'wasb_default' for task execution.
[2023-01-31 17:13:51,878] {base.py:68} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-31 17:13:51,879] {azure_blob_to_gcs.py:108} INFO - Downloading data from blob: retail_2021.csv
[2023-01-31 17:13:53,463] {azure_blob_to_gcs.py:114} INFO - Uploading data from blob's: retail_2021_azure.csv into GCP bucket: azure_airflow23
[2023-01-31 17:13:53,763] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/transfers/azure_blob_to_gcs.py", line 117, in execute
    gcs_hook.upload(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 517, in upload
    _call_with_retry(
  File "/home/tinmar/.local/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 475, in _call_with_retry
    f()
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2683, in upload_from_filename
    self.upload_from_file(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2539, in upload_from_file
    created_json = self._do_upload(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2354, in _do_upload
    response = self._do_multipart_upload(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1889, in _do_multipart_upload
    response = upload.transmit(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 148, in wait_and_retry
    response = func()
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 145, in retriable_request
    result = transport.request(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/auth/transport/requests.py", line 545, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/auth/credentials.py", line 135, in before_request
    self.refresh(request)
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/oauth2/service_account.py", line 429, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/oauth2/_client.py", line 294, in jwt_grant
    response_data = _token_endpoint_request(
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/oauth2/_client.py", line 265, in _token_endpoint_request
    _handle_error_response(response_data, retryable_error)
  File "/home/tinmar/.local/lib/python3.10/site-packages/google/oauth2/_client.py", line 69, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'})
[2023-01-31 17:13:53,776] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=2.3_azure_storage_bigquery, task_id=transferir_azure_2021, execution_date=20230131T000000, start_date=20230201T001351, end_date=20230201T001353
[2023-01-31 17:13:53,801] {standard_task_runner.py:92} ERROR - Failed to execute job 83 for task transferir_azure_2021 (('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'}); 13475)
[2023-01-31 17:13:53,806] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-31 17:13:53,860] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
