[2023-02-21T08:48:32.104-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-02-21T08:48:32.125-0600] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-20T00:00:00+00:00 [queued]>
[2023-02-21T08:48:32.126-0600] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T08:48:32.126-0600] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-02-21T08:48:32.128-0600] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-21T08:48:32.144-0600] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): insert_data> on 2023-02-20 00:00:00+00:00
[2023-02-21T08:48:32.149-0600] {standard_task_runner.py:54} INFO - Started process 428133 to run task
[2023-02-21T08:48:32.153-0600] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1.5_user_processing', 'insert_data', 'scheduled__2023-02-20T00:00:00+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/Introduction_to_Apache_Airflow/1.5_user_processing.py', '--cfg-path', '/tmp/tmpurr_qhzf']
[2023-02-21T08:48:32.156-0600] {standard_task_runner.py:83} INFO - Job 613: Subtask insert_data
[2023-02-21T08:48:32.158-0600] {dagbag.py:525} INFO - Filling up the DagBag from /c/Airflow/dags/Introduction_to_Apache_Airflow/1.5_user_processing.py
[2023-02-21T08:48:32.891-0600] {task_command.py:384} INFO - Running <TaskInstance: 1.5_user_processing.insert_data scheduled__2023-02-20T00:00:00+00:00 [running]> on host Tinmar.
[2023-02-21T08:48:32.982-0600] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Tinmar
AIRFLOW_CTX_DAG_ID=1.5_user_processing
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-20T00:00:00+00:00
[2023-02-21T08:48:32.984-0600] {sql.py:254} INFO - Executing: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    
[2023-02-21T08:48:33.004-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-21T08:48:33.390-0600] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-02-21T08:48:33.401-0600] {sql.py:375} INFO - Running statement: 
                                        INSERT INTO users VALUES ('Tinmar', 'Andrade','México','tinmar','GuruSat.3','tinmar96@gmail.com')
                                    , parameters: None
[2023-02-21T08:48:33.403-0600] {sql.py:384} INFO - Rows affected: 1
[2023-02-21T08:48:33.425-0600] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=1.5_user_processing, task_id=insert_data, execution_date=20230220T000000, start_date=20230221T144832, end_date=20230221T144833
[2023-02-21T08:48:33.490-0600] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-02-21T08:48:33.530-0600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
